### ISSUE TITLE
merge drc libbot fork

### ISSUE THREAD

**Issue by mauricefallon** [RobotLocomotion/libbot#11]
I manually move each commit from libbot-drc to mitdrc/libbot
- I figured out that libbot was forked at b8cfe1a656454cdd08db4d6011ac8b421455a002
- this was r7667 of the DRC svn repository.
  Below are the commits that were made. I skipped a few that weren't useful.

This is on this branch:
https://github.com/mitdrc/libbot/tree/mfallon-merge-libbot-drc-changes-alpah
Which is based off of b8cfe1a. 

---

r8334 | antone | 2015-03-10 15:35:41 +0000 (Tue, 10 Mar 2015) | 1 line
## reconcile running state of sheriff with that of deputy at startup; this fixes behavior that erroneously starts stopped processes on sheriff restart

r8332 | russt | 2014-12-23 20:16:03 +0000 (Tue, 23 Dec 2014) | 1 line
## obj support update from Russ

r8331 | antone | 2014-11-24 02:05:39 +0000 (Mon, 24 Nov 2014) | 1 line
## added bot_core::images_t

r8329 | mfallon | 2014-08-28 01:45:21 +0100 (Thu, 28 Aug 2014) | 1 line
## minor mod to param server republishing

r8328 | antone | 2014-08-28 00:28:37 +0100 (Thu, 28 Aug 2014) | 1 line
## added lcm message based initialization for param server

r8325 | russt | 2014-03-25 16:08:52 +0000 (Tue, 25 Mar 2014) | 1 line
## merge in change from github: enabling depth tests in lcmgl renderer

r8324 | russt | 2014-03-25 16:08:08 +0000 (Tue, 25 Mar 2014) | 1 line
## merge change from github / libbot: make start/stop recording methods public

r8323 | antone | 2014-03-24 16:39:36 +0000 (Mon, 24 Mar 2014) | 1 line
## fixed memory leak in which freeing elements from middle of config block would leave next elements unreferenced

r8322 | antone | 2014-03-21 21:11:32 +0000 (Fri, 21 Mar 2014) | 1 line
## fixed bug in string array parsing

r8149 | antone | 2013-12-10 19:42:58 +0000 (Tue, 10 Dec 2013) | 1 line
## fixed bug in param server value update when not an array

SKIPPED r7971 | mfallon | 2013-12-06 00:37:47 +0000 (Fri, 06 Dec 2013) | 1 line
## adding printf request mesg

SKIPPED r7969 | mfallon | 2013-12-06 00:17:57 +0000 (Fri, 06 Dec 2013) | 1 line
## adding fetch printf capability

SKIPPED r7946 | mfallon | 2013-12-05 20:38:51 +0000 (Thu, 05 Dec 2013) | 1 line
## removing restart button

r7762 | russt | 2013-11-27 19:30:08 +0000 (Wed, 27 Nov 2013) | 1 line
## merged non-Apple fix from main libbot

r7688 | antone | 2013-11-26 14:30:11 +0000 (Tue, 26 Nov 2013) | 1 line
## fixed bugs in param client and server that prevented proper external 'set_x' methods from working properly; added new message field that distinguishes between different set types

r7687 | antone | 2013-11-26 14:28:01 +0000 (Tue, 26 Nov 2013) | 1 line
## reverted russ's cmake changes from libbot head that were accidentally included in the clone

r7667 | antone | 2013-11-25 21:51:33 +0000 (Mon, 25 Nov 2013) | 1 line

**Comment by mauricefallon** [comment]
I intend to remove svn usage from mitdrc/drc first and to then move to rebase and merge this branch into RL/libbot

**Comment by RussTedrake** [comment]
@mauricefallon -- is this done?  which version (if any) are you using in oh-distro?

**Comment by mauricefallon** [comment]
We are using this:
https://github.com/openhumanoids/libbot/tree/libbot-openhumanoids
I'll work to merge it in this week. There was one conflict (some thing with gtk/Apple that Pat introduced). 

This branch disables building the bot_core lcmtypes in favour of building them seperately, as we were discussing

**Comment by RussTedrake** [comment]
Thanks @mauricefallon .

**Comment by jamiesnape** [comment]
This repository is deprecated. Please contribute to the upstream https://github.com/libbot2/libbot2 or the new fork https://github.com/RobotLocomotion/libbot2 instead.
