### ISSUE TITLE
This repo is not forked from upstream

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/libbot#21]
This repository is not forked off of what appears to be the (current) canonical upstream, https://github.com/libbot2/libbot, and the history is out of sync.

I propose that someone with sufficient permissions:
- [ ] Push a copy of the current master to some new branch name (to prevent garbage collection from pruning the old history until forks can be updates).
- [ ] Reset master to mwoehlke-kitware/libbot@e7ff4150c275, which has the same content as current master (@a889c5f10f31), but meshes with the upstream history.
- [ ] Ask github to attach this repo as a fork of https://github.com/libbot2/libbot so that PR's can be made between us and upstream.

**Comment by jamiesnape** [comment]
Pinging @david-german-tri.

**Comment by david-german-tri** [comment]
Hmm.  Alternatively, could we just fork the canonical upstream into a new repo, push our patches to it, cut Drake & co over, and then delete this repo once we're really sure it's dead?  That seems like it has a few advantages:

- No rewriting public history
- Canonicalize on the new `libbot2` name
- Don't have to talk to GitHub support (can they even make the "fork" link post facto?)

**Comment by jamiesnape** [comment]
I like that plan. Quite convenient the upstream repo is not called `libbot`.

**Comment by mwoehlke-kitware** [comment]
>  Alternatively, could we just fork the canonical upstream into a new repo

This just pushes the problem downstream, by detaching us from the (non-trivial) network of forks of *this* repo. We'd force everyone else to do the same, and we'd lose history (*all* issues and PR's in *all* downstream repos) in the process.

> No rewriting public history

Either way, we need to point `master` at the aforementioned SHA (which is not in upstream). Anyway, I proposed to keep the old history, maybe even indefinitely (so old PR's will still point somewhere).

> Don't have to talk to GitHub support (can they even make the "fork" link post facto?)

I believe so; at least, I found a page somewhere (SO?) that suggests they can. Possibly we could even ask first, as I think adding the fork relationship doesn't actually require shared history.

> Canonicalize on the new libbot2 name

If that's desirable, it's trivial and less disruptive / destructive to just rename this repo.

**Comment by david-german-tri** [comment]
OK, those are good points.  I'll contact GitHub support.

**Comment by david-german-tri** [comment]
They say:

> Cross-network reparenting isn’t possible at this time. If the two repository existed in the same network, we may have been able to assist with this, but looking at them on our side, this wouldn't be possible.

**Comment by david-german-tri** [comment]
I just talked to @gizatt about this, and he says his branches will be fine.

@patmarion, @wxmerkt, would it cause problems for you if Drake switched to a new `RobotLocomotion/libbot2` repository, which is a fork of upstream https://github.com/libbot2/libbot?  `master` in the new repo would have the exact same source code as this repo does right now, but a history that was consistent with upstream development.

**Comment by patmarion** [comment]
fine with me, thanks for working on it!

**Comment by mwoehlke-kitware** [comment]
Updated SHA (including #22) is 83d56d663ac9.

**Comment by david-german-tri** [comment]
We probably won't hear from @wxmerkt until tomorrow AM due to time zones, so let's table until then.

**Comment by wxmerkt** [comment]
@david-german-tri No problems here, thanks for checking :)

**Comment by david-german-tri** [comment]
Fork: https://github.com/RobotLocomotion/libbot2

**Comment by david-german-tri** [comment]
@mwoehlke-kitware, please go ahead and PR your stack of commits, then cut Drake over!

**Comment by mwoehlke-kitware** [comment]
New (properly forked) repo is https://github.com/RobotLocomotion/libbot2
