### ISSUE TITLE
lcmgl_bot_renderer.h header not installed

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/libbot#6]
The `lcmgl_bot_renderer.h` header isn't installed when building bot_lcmgl_renderer, which causes the bot-lcmgl build to fail later on. Has anyone else had this problem? 

It's an easy fix, and I can open a pull request for it, but I'm curious if maybe it's just something wrong with my system (since I would expect this to cause the build to fail for everyone, which doesn't seem to be the case).

**Comment by cdarpino** [comment]
FYI I got this error after last update to libbot.


-------------------------------------------
-- bot2-lcmgl
-------------------------------------------

BUILD_PREFIX: /home/drc/build


-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'lcm'
--   found lcm, version 1.1.0
-- Found Java: /usr/bin/java (found version "1.6.0.34") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/drc/DIRECTOR_PLANNING_TEST/drake-distro/libbot/bot2-lcmgl/pod-build
Scanning dependencies of target lcmgen_c
[  0%] Built target lcmgen_c
Scanning dependencies of target lcmgen_cpp
[  0%] Built target lcmgen_cpp
Scanning dependencies of target lcmgen_java
[  0%] Built target lcmgen_java
Scanning dependencies of target lcmgen_python
[  0%] Built target lcmgen_python
Scanning dependencies of target lcmtypes_bot2-lcmgl
[ 11%] Building C object CMakeFiles/lcmtypes_bot2-lcmgl.dir/lcmtypes/c/lcmtypes/bot_lcmgl_data_t.c.o
Linking C static library lib/liblcmtypes_bot2-lcmgl.a
[ 11%] Built target lcmtypes_bot2-lcmgl
Scanning dependencies of target bot2-lcmgl-client
[ 22%] Building C object src/bot_lcmgl_client/CMakeFiles/bot2-lcmgl-client.dir/lcmgl.c.o
Linking C shared library ../../lib/libbot2-lcmgl-client.so
[ 22%] Built target bot2-lcmgl-client
Scanning dependencies of target bot2-lcmgl-renderer
[ 33%] Building C object src/bot_lcmgl_render/CMakeFiles/bot2-lcmgl-renderer.dir/lcmgl_decode.c.o
[ 44%] Building C object src/bot_lcmgl_render/CMakeFiles/bot2-lcmgl-renderer.dir/lcmgl_bot_renderer.c.o
Linking C shared library ../../lib/libbot2-lcmgl-renderer.so
[ 44%] Built target bot2-lcmgl-renderer
Scanning dependencies of target bot-lcmgl-viewer
[ 55%] Building C object src/lcmgl-viewer/CMakeFiles/bot-lcmgl-viewer.dir/main.c.o
/home/drc/DIRECTOR_PLANNING_TEST/drake-distro/libbot/bot2-lcmgl/src/lcmgl-viewer/main.c:8:49: fatal error: bot_lcmgl_render/lcmgl_bot_renderer.h: No such file or directory
 #include <bot_lcmgl_render/lcmgl_bot_renderer.h>
                                                 ^
compilation terminated.
make[5]: *** [src/lcmgl-viewer/CMakeFiles/bot-lcmgl-viewer.dir/main.c.o] Error 1
make[4]: *** [src/lcmgl-viewer/CMakeFiles/bot-lcmgl-viewer.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by rdeits** [comment]
It looks like this is fixed in RobotLocomotion/master. The drake-distro submodule reference just needs to be updated to point to master.

**Comment by RussTedrake** [comment]
ah yes.  i found and fixed that one the other day. good catch.

**Comment by cdarpino** [comment]
Yes, libbot master works here as well, so drake-distro need to point to libbot master

**Comment by RussTedrake** [comment]
just pushed updated submodule ref to drake-distro.
