### ISSUE TITLE
adding some drc lcm msgs to libbot?

### ISSUE THREAD

**Issue by mauricefallon** [RobotLocomotion/libbot#8]
bot_core is missing a couple of the standard lcmtypes we used in the DRC: generic point cloud, IMU, joint state and presumably robot_state_t. Other to consider would be robot_urdf_t and force_torque_t

@patmarion and @RussTedrake would you find it useful to define standard types like this for future applications? 

For pronto I keep having to redefine DRC types in pronto. Ideally there would be a submodule just with lcmtypes that I could use in my distro repo.

(Also, moving to use this repo in the mitdrc/drc would be good)

BTW, ROS has a set of clear and fully static standard sensor messages:
http://wiki.ros.org/sensor_msgs

**Comment by patmarion** [comment]
I would like a common repo for these lcm types.  Maybe it's even better if the repo was just lcm types and not part of libbot, but I'd be open to either scenario.  Part of making director standalone requires the basic robot types (for planning) which are only provided by drc lcmtypes at the moment.

**Comment by patmarion** [comment]
Here are all the lcmtypes imported by python in the director.  Note, only a few of these messages are required for robot display and ik planning.

affordance_collection_t
atlas_battery_data_t
atlas_behavior_command_t
atlas_behavior_manipulate_params_t
atlas_behavior_pelvis_servo_params_t
atlas_behavior_step_params_t
atlas_electric_arm_enable_t
atlas_electric_arm_status_t
atlas_pump_command_t
atlas_state_extra_t
atlas_state_t
atlas_status_t
atlas_strain_gauges_t
auto_iris_segmentation_request_t
block_fit_request_t
boolean_t
data_request_list_t
data_request_t
driving_control_cmd_t
foot_contact_estimate_t
footstep_check_request_t
footstep_params_t
footstep_plan_params_t
footstep_plan_request_t
footstep_plan_t
footstep_t
force_torque_t
gamepad_cmd_t
image_roi_t
iris_region_request_t
iris_region_response_t
iris_region_t
joint_angles_t
joint_position_goal_t
lin_con_t
message_rate_t
neck_pitch_t
pfgrasp_command_t
plan_adjust_mode_t
plan_control_t
planner_request_t
plan_status_t
position_3d_t
position_t
quaternion_t
recovery_trigger_t
robot_plan_t
robot_plan_with_supports_t
robot_plan_w_keyframes_t
robot_state_t
robot_urdf_t
subimage_request_t
support_body_t
support_element_t
system_status_t
tag_detection_t
terrain_raycast_request_t
trigger_finger_t
twist_t
utime_t
vector_3d_t
walking_plan_request_t
walking_plan_t

**Comment by jamiesnape** [comment]
This repository is deprecated. Please contribute to the upstream https://github.com/libbot2/libbot2 or the new fork https://github.com/RobotLocomotion/libbot2 instead.
