### ISSUE TITLE
pods.cmake calls get_target_property for non-targets

### ISSUE THREAD

**Issue by patmarion** [RobotLocomotion/libbot#9]
For previous discussion, see: https://github.com/RobotLocomotion/libbot/commit/db3e32c23e7d860775e948372a1f6b301be48440#commitcomment-12640480

I just had a closer look at the offending code in pods.cmake, it says:

    get_target_property(IS_TARGET ${__depend_target_name} LOCATION)
    if (NOT IS_TARGET STREQUAL "IS_TARGET-NOTFOUND")
      ...
    endif()

In CMake you can test whether a name is a target with:

    if(TARGET ${__depend_target_name})

Code like this already exists in pods.cmake provided by RobotLocomotion/cmake.git

Maybe a low priority issue, but with this fix it could avoid setting the policy to OLD.  I think it's best not to set policy to OLD because it can cover other bugs.

**Comment by patmarion** [comment]
Actually, in cmake 2.8 (ubuntu 14.04):

CMake Error at CMakeLists.txt:2 (cmake_policy):
  Policy "CMP0045" is not known to this version of CMake.

So maybe it's worth making this change now?  I'm happy to do it if you think it's the right fix @RussTedrake

**Comment by RussTedrake** [comment]
Perhaps the best fix is to make libbot use the cmake submodule?
